FROM golang:1.23.4 as build

COPY . /go/src

WORKDIR /go/src/cmd/gophkeeper

RUN CGO_ENABLED=0 GOOS=linux go build -o /server

FROM alpine:latest

COPY --from=build server .

EXPOSE 8000

ENTRYPOINT [ "/server" ]

