FROM node:20.11.1-alpine as node-build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json tsconfig.json vite.config.ts /app/

RUN npm i
COPY . /app

RUN npm run build


FROM nginx:1.23-alpine

COPY --from=node-build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8001

CMD ["nginx", "-g", "daemon off;"]
